package com.springcloud.dao;

import com.springcloud.entity.Class2;
import java.util.List;

public interface Class2Mapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table class2
	 *
	 * @mbg.generated Wed May 22 10:08:06 CST 2019
	 */
	int deleteByPrimaryKey(Integer class2Id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table class2
	 *
	 * @mbg.generated Wed May 22 10:08:06 CST 2019
	 */
	int insert(Class2 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table class2
	 *
	 * @mbg.generated Wed May 22 10:08:06 CST 2019
	 */
	Class2 selectByPrimaryKey(Integer class2Id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table class2
	 *
	 * @mbg.generated Wed May 22 10:08:06 CST 2019
	 */
	List<Class2> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table class2
	 *
	 * @mbg.generated Wed May 22 10:08:06 CST 2019
	 */
	int updateByPrimaryKey(Class2 record);

	/**
	 * 查询class2表中指定class1的二级类别信息
	 * 
	 * @param class1Id 一级类别编号
	 * @return 成功返回java.util.List类型的实例，否则返回null
	 */
	public abstract List<Class2> selectByClass1Id(Integer class1Id);
}