package com.springcloud.dao;

import com.springcloud.entity.Orders;
import java.util.List;

public interface OrdersMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table orders
	 *
	 * @mbg.generated Fri May 31 16:47:52 CST 2019
	 */
	int deleteByPrimaryKey(Integer orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table orders
	 *
	 * @mbg.generated Fri May 31 16:47:52 CST 2019
	 */
	int insert(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table orders
	 *
	 * @mbg.generated Fri May 31 16:47:52 CST 2019
	 */
	Orders selectByPrimaryKey(Integer orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table orders
	 *
	 * @mbg.generated Fri May 31 16:47:52 CST 2019
	 */
	List<Orders> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table orders
	 *
	 * @mbg.generated Fri May 31 16:47:52 CST 2019
	 */
	int updateByPrimaryKey(Orders record);

	/**
	 * 查询Orders表中满足条件的订单信息
	 * 
	 * @param orders 查询条件
	 * @return 成功返回java.util.List类型的实例，否则返回null
	 */
	public abstract List<Orders> selectOrders(Orders orders);

	/**
	 * 修改Orders表中指定Order_id订单的信息
	 * 
	 * @param orders 修改订单的信息
	 * @return 成功返回大于0的整数，否则返回小于等于0的整数
	 */
	public abstract Integer updateOrderStatus(Orders orders);

	/**
	 * 查询指定日期范围内的销售额
	 * 
	 * @param orders 查询条件
	 * @return 成功返回java.util.List类型的实例，否则返回null
	 */
	public abstract List<Orders> selectGroup(Orders orders);
}